export const links: TopicLink[] = [
  {
    publisher: "CNN",
    topic: "Opinion",
    slug: "cnn-opinion",
    url: "http://rss.cnn.com/rss/cnn_opinion.rss",
    sectionHints: ["commentaries", "politics"],
  },
  {
    publisher: "The Guardian",
    topic: "Comment is Free",
    slug: "guardian-comment-is-free",
    url: "https://www.theguardian.com/commentisfree/rss",
    sectionHints: ["commentaries", "international"],
  },
  {
    publisher: "BBC",
    topic: "News",
    slug: "bbc-news",
    url: "https://feeds.bbci.co.uk/news/rss.xml",
    sectionHints: ["international"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Asia",
    slug: "cna-asia",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
    sectionHints: ["international"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Business",
    slug: "cna-business",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
    sectionHints: ["business-tech"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Latest",
    slug: "cna-latest",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
    sectionHints: ["international", "politics", "business-tech"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Singapore",
    slug: "cna-singapore",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
    sectionHints: ["politics"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Sport",
    slug: "cna-sport",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10296",
    sectionHints: ["wildcard"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "World",
    slug: "cna-world",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6311",
    sectionHints: ["international"],
  },
  {
    publisher: "BBC",
    topic: "World",
    slug: "bbc-world",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    sectionHints: ["international"],
  },
  {
    publisher: "BBC",
    topic: "Business",
    slug: "bbc-business",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    sectionHints: ["business-tech"],
  },
  {
    publisher: "CNN",
    topic: "Top Stories",
    slug: "cnn-top-stories",
    url: "http://rss.cnn.com/rss/edition.rss",
    sectionHints: ["international", "politics"],
  },
  {
    publisher: "NPR",
    topic: "Top Stories",
    slug: "npr-top-stories",
    url: "https://feeds.npr.org/1001/rss.xml",
    sectionHints: ["international", "politics"],
  },
  {
    publisher: "Al Jazeera",
    topic: "All Articles",
    slug: "al-jazeera-all",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    sectionHints: ["international", "politics"],
  },
];
