export const links: TopicLink[] = [
  {
    publisher: "The Guardian",
    topic: "Comment is Free",
    slug: "guardian-comment-is-free",
    url: "https://www.theguardian.com/commentisfree/rss",
    sectionHints: ["commentaries", "international"],
    description:
      "Columns and essays offering diverse perspectives from The Guardian.",
    region: "UK",
    language: "en",
    tags: ["commentaries", "essays"],
  },
  {
    publisher: "BBC",
    topic: "News",
    slug: "bbc-news",
    url: "https://feeds.bbci.co.uk/news/rss.xml",
    sectionHints: ["international"],
    description: "Top headlines and breaking news from the BBC.",
    region: "INT",
    language: "en",
    tags: ["headlines", "breaking"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Asia",
    slug: "cna-asia",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
    sectionHints: ["international"],
    description: "Regional coverage focused on Asian news and developments.",
    region: "ASIA",
    language: "en",
    tags: ["regional", "asia"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Business",
    slug: "cna-business",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
    sectionHints: ["business"],
    description: "Business and markets news relevant to Asia-Pacific.",
    region: "ASIA",
    language: "en",
    tags: ["business", "markets"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Latest",
    slug: "cna-latest",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
    sectionHints: ["international", "politics", "business", "tech"],
    description: "Latest updates across topics from CNA.",
    region: "ASIA",
    language: "en",
    tags: ["latest", "updates"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Singapore",
    slug: "cna-singapore",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
    sectionHints: ["politics"],
    description: "News and politics from Singapore.",
    region: "SG",
    language: "en",
    tags: ["singapore", "local"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Sport",
    slug: "cna-sport",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10296",
    sectionHints: ["sport"],
    description: "Sports coverage and scores from CNA.",
    region: "ASIA",
    language: "en",
    tags: ["sport"],
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "World",
    slug: "cna-world",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6311",
    sectionHints: ["international"],
    description: "Global headlines curated by CNA.",
    region: "INT",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "BBC",
    topic: "World",
    slug: "bbc-world",
    url: "https://feeds.bbci.co.uk/news/world/rss.xml",
    sectionHints: ["international"],
    description: "Global news and analysis from the BBC world desk.",
    region: "INT",
    language: "en",
    tags: ["world"],
  },
  {
    publisher: "BBC",
    topic: "Business",
    slug: "bbc-business",
    url: "https://feeds.bbci.co.uk/news/business/rss.xml",
    sectionHints: ["business"],
    description: "Business news, markets, and economy from the BBC.",
    region: "INT",
    language: "en",
    tags: ["business", "economy"],
  },
  {
    publisher: "NPR",
    topic: "Top Stories",
    slug: "npr-top-stories",
    url: "https://feeds.npr.org/1001/rss.xml",
    sectionHints: ["international", "politics"],
    description: "NPR's top stories and features.",
    region: "US",
    language: "en",
    tags: ["features", "audio"],
  },
  {
    publisher: "Al Jazeera",
    topic: "All Articles",
    slug: "al-jazeera-all",
    url: "https://www.aljazeera.com/xml/rss/all.xml",
    sectionHints: ["international", "politics"],
    description: "Comprehensive reporting and analysis from Al Jazeera.",
    region: "INT",
    language: "en",
    tags: ["investigations", "international"],
  },
  {
    publisher: "The Straits Times",
    topic: "World",
    slug: "st-world",
    url: "https://www.straitstimes.com/news/world/rss.xml",
    sectionHints: ["international"],
    description:
      "Global news and international affairs from The Straits Times.",
    region: "ASIA",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "The Straits Times",
    topic: "Business",
    slug: "st-business",
    url: "https://www.straitstimes.com/news/business/rss.xml",
    sectionHints: ["business"],
    description: "Business news and economic coverage from The Straits Times.",
    region: "ASIA",
    language: "en",
    tags: ["business", "economy"],
  },
  {
    publisher: "The Straits Times",
    topic: "Sport",
    slug: "st-sport",
    url: "https://www.straitstimes.com/news/sport/rss.xml",
    sectionHints: ["sport"],
    description: "Sports coverage and updates from The Straits Times.",
    region: "ASIA",
    language: "en",
    tags: ["sport"],
  },
  {
    publisher: "The Straits Times",
    topic: "Opinion",
    slug: "st-opinion",
    url: "https://www.straitstimes.com/news/opinion/rss.xml",
    sectionHints: ["commentaries"],
    description: "Commentaries columns and editorials from The Straits Times.",
    region: "ASIA",
    language: "en",
    tags: ["commentaries", "editorials"],
  },
  {
    publisher: "The Straits Times",
    topic: "Singapore",
    slug: "st-singapore",
    url: "https://www.straitstimes.com/news/singapore/rss.xml",
    sectionHints: ["politics"],
    description: "Singapore news and local politics from The Straits Times.",
    region: "SG",
    language: "en",
    tags: ["singapore", "local"],
  },
  {
    publisher: "The Straits Times",
    topic: "Asia",
    slug: "st-asia",
    url: "https://www.straitstimes.com/news/asia/rss.xml",
    sectionHints: ["international"],
    description: "Asian regional news from The Straits Times.",
    region: "ASIA",
    language: "en",
    tags: ["asia", "regional"],
  },
  {
    publisher: "The Straits Times",
    topic: "Tech",
    slug: "st-tech",
    url: "https://www.straitstimes.com/news/tech/rss.xml",
    sectionHints: ["tech"],
    description:
      "Technology news and digital innovation from The Straits Times.",
    region: "ASIA",
    language: "en",
    tags: ["tech", "innovation"],
  },
  {
    publisher: "TechRadar",
    topic: "News",
    slug: "techradar-news",
    url: "https://www.techradar.com/feeds.xml",
    sectionHints: ["tech"],
    description: "Latest technology news, reviews, and gadgets from TechRadar.",
    region: "INT",
    language: "en",
    tags: ["tech", "gadgets", "reviews"],
  },
  {
    publisher: "CNBC",
    topic: "Economy",
    slug: "cnbc-economy",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=20910258",
    sectionHints: ["business"],
    description: "Economy news and analysis from CNBC.",
    region: "US",
    language: "en",
    tags: ["economy", "business"],
  },
  {
    publisher: "CNBC",
    topic: "Media",
    slug: "cnbc-media",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000110",
    sectionHints: ["business", "tech"],
    description: "Media industry news from CNBC.",
    region: "US",
    language: "en",
    tags: ["media", "business"],
  },
  {
    publisher: "CNBC",
    topic: "Business",
    slug: "cnbc-business",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10001147",
    sectionHints: ["business"],
    description: "Business news from CNBC.",
    region: "US",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "CNBC",
    topic: "Commentary",
    slug: "cnbc-commentary",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100370673",
    sectionHints: ["commentaries"],
    description: "Commentary and commentaries from CNBC.",
    region: "US",
    language: "en",
    tags: ["commentary", "commentaries"],
  },
  {
    publisher: "CNBC",
    topic: "Tech",
    slug: "cnbc-tech",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=19854910",
    sectionHints: ["tech"],
    description: "Technology news from CNBC.",
    region: "US",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "CNBC",
    topic: "Politics",
    slug: "cnbc-politics",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=10000113",
    sectionHints: ["politics"],
    description: "Political news from CNBC.",
    region: "US",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "CNBC",
    topic: "International News",
    slug: "cnbc-international-news",
    url: "https://search.cnbc.com/rs/search/combinedcms/view.xml?partnerId=wrss01&id=100727362",
    sectionHints: ["international"],
    description: "International news from CNBC.",
    region: "US",
    language: "en",
    tags: ["international", "news"],
  },
  {
    publisher: "BBC",
    topic: "Politics",
    slug: "bbc-politics",
    url: "https://feeds.bbci.co.uk/news/politics/rss.xml",
    sectionHints: ["politics"],
    description: "Political news from the BBC.",
    region: "INT",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "BBC",
    topic: "Technology",
    slug: "bbc-technology",
    url: "https://feeds.bbci.co.uk/news/technology/rss.xml",
    sectionHints: ["tech"],
    description: "Technology news from the BBC.",
    region: "INT",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "BBC",
    topic: "Entertainment and Arts",
    slug: "bbc-entertainment-and-arts",
    url: "https://feeds.bbci.co.uk/news/entertainment_and_arts/rss.xml",
    sectionHints: ["entertainment", "culture"],
    description: "Entertainment and arts news from the BBC.",
    region: "INT",
    language: "en",
    tags: ["entertainment", "arts", "culture"],
  },
  {
    publisher: "The Washington Post",
    topic: "Opinions",
    slug: "washingtonpost-opinions",
    url: "https://www.washingtonpost.com/arcio/rss/category/opinions/",
    sectionHints: ["commentaries"],
    description: "Commentaries and editorials from The Washington Post.",
    region: "US",
    language: "en",
    tags: ["commentaries", "editorials"],
  },
  {
    publisher: "The Washington Post",
    topic: "Politics",
    slug: "washingtonpost-politics",
    url: "https://www.washingtonpost.com/arcio/rss/category/politics/",
    sectionHints: ["politics"],
    description: "Political news from The Washington Post.",
    region: "US",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "The Washington Post",
    topic: "Business Technology",
    slug: "washingtonpost-business-technology",
    url: "https://feeds.washingtonpost.com/rss/business/technology",
    sectionHints: ["business", "tech"],
    description: "Business and technology news from The Washington Post.",
    region: "US",
    language: "en",
    tags: ["business", "tech", "technology"],
  },
  {
    publisher: "The Washington Post",
    topic: "World",
    slug: "washingtonpost-world",
    url: "https://feeds.washingtonpost.com/rss/world",
    sectionHints: ["international"],
    description: "World news from The Washington Post.",
    region: "US",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "The Washington Post",
    topic: "Business",
    slug: "washingtonpost-business",
    url: "https://feeds.washingtonpost.com/rss/business",
    sectionHints: ["business"],
    description: "Business news from The Washington Post.",
    region: "US",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "Los Angeles Times",
    topic: "Business",
    slug: "latimes-business",
    url: "https://www.latimes.com/business/rss2.0.xml",
    sectionHints: ["business"],
    description: "Business news from the Los Angeles Times.",
    region: "US",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "Los Angeles Times",
    topic: "Opinion",
    slug: "latimes-opinion",
    url: "https://www.latimes.com/opinion/rss2.0.xml",
    sectionHints: ["commentaries"],
    description: "Commentaries from the Los Angeles Times.",
    region: "US",
    language: "en",
    tags: ["commentaries"],
  },
  {
    publisher: "Los Angeles Times",
    topic: "Politics",
    slug: "latimes-politics",
    url: "https://www.latimes.com/politics/rss2.0.xml",
    sectionHints: ["politics"],
    description: "Political news from the Los Angeles Times.",
    region: "US",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "Los Angeles Times",
    topic: "World Nation",
    slug: "latimes-world-nation",
    url: "https://www.latimes.com/world-nation/rss2.0.xml",
    sectionHints: ["international"],
    description: "World and national news from the Los Angeles Times.",
    region: "US",
    language: "en",
    tags: ["world", "national", "international"],
  },
  {
    publisher: "CBC",
    topic: "Top Stories",
    slug: "cbc-topstories",
    url: "https://www.cbc.ca/webfeed/rss/rss-topstories",
    sectionHints: ["international"],
    description: "Top stories from CBC.",
    region: "CA",
    language: "en",
    tags: ["top", "stories"],
  },
  {
    publisher: "CBC",
    topic: "World",
    slug: "cbc-world",
    url: "https://www.cbc.ca/webfeed/rss/rss-world",
    sectionHints: ["international"],
    description: "World news from CBC.",
    region: "CA",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "CBC",
    topic: "Politics",
    slug: "cbc-politics",
    url: "https://www.cbc.ca/webfeed/rss/rss-politics",
    sectionHints: ["politics"],
    description: "Political news from CBC.",
    region: "CA",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "CBC",
    topic: "Business",
    slug: "cbc-business",
    url: "https://www.cbc.ca/webfeed/rss/rss-business",
    sectionHints: ["business"],
    description: "Business news from CBC.",
    region: "CA",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "CBC",
    topic: "Technology",
    slug: "cbc-technology",
    url: "https://www.cbc.ca/webfeed/rss/rss-technology",
    sectionHints: ["tech"],
    description: "Technology news from CBC.",
    region: "CA",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "National Post",
    topic: "All",
    slug: "nationalpost-all",
    url: "https://nationalpost.com/feed/atom",
    sectionHints: ["international"],
    description: "News from the National Post.",
    region: "CA",
    language: "en",
    tags: ["news"],
  },
  {
    publisher: "Google News",
    topic: "Bloomberg Top Stories",
    slug: "googlenews-bloomberg-top-stories",
    url: "https://news.google.com/rss/search?q=when:24h+allinurl:bloomberg.com",
    sectionHints: ["business"],
    description: "Top stories from Bloomberg via Google News.",
    region: "INT",
    language: "en",
    tags: ["bloomberg", "top", "stories", "business"],
  },
  {
    publisher: "Bloomberg",
    topic: "Markets",
    slug: "bloomberg-markets",
    url: "https://feeds.bloomberg.com/markets/news.rss",
    sectionHints: ["business"],
    description: "Markets news from Bloomberg.",
    region: "INT",
    language: "en",
    tags: ["markets", "business"],
  },
  {
    publisher: "Bloomberg",
    topic: "Politics",
    slug: "bloomberg-politics",
    url: "https://feeds.bloomberg.com/politics/news.rss",
    sectionHints: ["politics"],
    description: "Political news from Bloomberg.",
    region: "INT",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "Bloomberg",
    topic: "Technology",
    slug: "bloomberg-technology",
    url: "https://feeds.bloomberg.com/technology/news.rss",
    sectionHints: ["tech"],
    description: "Technology news from Bloomberg.",
    region: "INT",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "The Wall Street Journal",
    topic: "Opinion",
    slug: "wsj-opinion",
    url: "https://feeds.content.dowjones.io/public/rss/RSSOpinion",
    sectionHints: ["commentaries"],
    description: "Commentaries from The Wall Street Journal.",
    region: "US",
    language: "en",
    tags: ["commentaries"],
  },
  {
    publisher: "The Wall Street Journal",
    topic: "World News",
    slug: "wsj-world-news",
    url: "https://feeds.content.dowjones.io/public/rss/RSSWorldNews",
    sectionHints: ["international"],
    description: "World news from The Wall Street Journal.",
    region: "US",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "The Wall Street Journal",
    topic: "Technology",
    slug: "wsj-technology",
    url: "https://feeds.content.dowjones.io/public/rss/RSSWSJD",
    sectionHints: ["tech"],
    description: "Technology news from The Wall Street Journal.",
    region: "US",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "The Wall Street Journal",
    topic: "Politics",
    slug: "wsj-politics",
    url: "https://feeds.content.dowjones.io/public/rss/socialpoliticsfeed",
    sectionHints: ["politics"],
    description: "Political news from The Wall Street Journal.",
    region: "US",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "The Wall Street Journal",
    topic: "US Business",
    slug: "wsj-us-business",
    url: "https://feeds.content.dowjones.io/public/rss/WSJcomUSBusiness",
    sectionHints: ["business"],
    description: "US business news from The Wall Street Journal.",
    region: "US",
    language: "en",
    tags: ["business", "us"],
  },
  {
    publisher: "ESPN",
    topic: "News",
    slug: "espn-news",
    url: "https://www.espn.com/espn/rss/news",
    sectionHints: ["sport"],
    description: "Sports news from ESPN.",
    region: "US",
    language: "en",
    tags: ["sports", "news"],
  },
  {
    publisher: "The Independent",
    topic: "World",
    slug: "independent-world",
    url: "https://www.independent.co.uk/news/world/rss",
    sectionHints: ["international"],
    description: "World news from The Independent.",
    region: "UK",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "The Independent",
    topic: "Sport",
    slug: "independent-sport",
    url: "https://www.independent.co.uk/sport/rss",
    sectionHints: ["sport"],
    description: "Sports news from The Independent.",
    region: "UK",
    language: "en",
    tags: ["sport"],
  },
  {
    publisher: "The Independent",
    topic: "Business",
    slug: "independent-business",
    url: "https://www.independent.co.uk/news/business/rss",
    sectionHints: ["business"],
    description: "Business news from The Independent.",
    region: "UK",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "The Guardian",
    topic: "International",
    slug: "guardian-international",
    url: "https://www.theguardian.com/international/rss",
    sectionHints: ["international"],
    description: "International news from The Guardian.",
    region: "UK",
    language: "en",
    tags: ["international"],
  },
  {
    publisher: "The Guardian",
    topic: "Middle East",
    slug: "guardian-middle-east",
    url: "https://www.theguardian.com/world/middleeast/rss",
    sectionHints: ["international"],
    description: "Middle East news from The Guardian.",
    region: "UK",
    language: "en",
    tags: ["middle-east", "international"],
  },
  {
    publisher: "The Guardian",
    topic: "US Politics",
    slug: "guardian-us-politics",
    url: "https://www.theguardian.com/us-news/us-politics/rss",
    sectionHints: ["politics"],
    description: "US political news from The Guardian.",
    region: "UK",
    language: "en",
    tags: ["us", "politics"],
  },
  {
    publisher: "The Guardian",
    topic: "UK Technology",
    slug: "guardian-uk-technology",
    url: "https://www.theguardian.com/uk/technology/rss",
    sectionHints: ["tech"],
    description: "UK technology news from The Guardian.",
    region: "UK",
    language: "en",
    tags: ["uk", "tech", "technology"],
  },
  {
    publisher: "The Guardian",
    topic: "Football",
    slug: "guardian-football",
    url: "https://www.theguardian.com/football/rss",
    sectionHints: ["sport"],
    description: "Football news from The Guardian.",
    region: "UK",
    language: "en",
    tags: ["football", "sport"],
  },
  {
    publisher: "The New York Times",
    topic: "World",
    slug: "nytimes-world",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/World.xml",
    sectionHints: ["international"],
    description: "World news from The New York Times.",
    region: "US",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "The New York Times",
    topic: "Politics",
    slug: "nytimes-politics",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml",
    sectionHints: ["politics"],
    description: "Political news from The New York Times.",
    region: "US",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "The New York Times",
    topic: "Business",
    slug: "nytimes-business",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
    sectionHints: ["business"],
    description: "Business news from The New York Times.",
    region: "US",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "The New York Times",
    topic: "Technology",
    slug: "nytimes-technology",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml",
    sectionHints: ["tech"],
    description: "Technology news from The New York Times.",
    region: "US",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "The New York Times",
    topic: "Arts",
    slug: "nytimes-arts",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Arts.xml",
    sectionHints: ["culture"],
    description: "Arts news from The New York Times.",
    region: "US",
    language: "en",
    tags: ["arts", "culture"],
  },
  {
    publisher: "The New York Times",
    topic: "Opinion",
    slug: "nytimes-opinion",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Opinion.xml",
    sectionHints: ["commentaries"],
    description: "Commentaries from The New York Times.",
    region: "US",
    language: "en",
    tags: ["commentaries"],
  },
  {
    publisher: "The New York Times",
    topic: "Science",
    slug: "nytimes-science",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/Science.xml",
    sectionHints: ["science"],
    description: "Science news from The New York Times.",
    region: "US",
    language: "en",
    tags: ["science"],
  },
  {
    publisher: "The Seattle Times",
    topic: "Entertainment",
    slug: "seattletimes-entertainment",
    url: "https://www.seattletimes.com/entertainment/feed/",
    sectionHints: ["entertainment"],
    description: "Entertainment news from The Seattle Times.",
    region: "US",
    language: "en",
    tags: ["entertainment"],
  },
  {
    publisher: "The Seattle Times",
    topic: "Life",
    slug: "seattletimes-life",
    url: "https://www.seattletimes.com/life/feed/",
    sectionHints: ["lifestyle"],
    description: "Lifestyle news from The Seattle Times.",
    region: "US",
    language: "en",
    tags: ["lifestyle"],
  },
  {
    publisher: "The Seattle Times",
    topic: "World",
    slug: "seattletimes-world",
    url: "https://www.seattletimes.com/world/feed/",
    sectionHints: ["international"],
    description: "World news from The Seattle Times.",
    region: "US",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "The Seattle Times",
    topic: "All",
    slug: "seattletimes-all",
    url: "https://www.seattletimes.com/feed/",
    sectionHints: ["international"],
    description: "All news from The Seattle Times.",
    region: "US",
    language: "en",
    tags: ["news"],
  },
  {
    publisher: "The Seattle Times",
    topic: "Opinion",
    slug: "seattletimes-opinion",
    url: "https://www.seattletimes.com/opinion/feed/",
    sectionHints: ["commentaries"],
    description: "Commentaries from The Seattle Times.",
    region: "US",
    language: "en",
    tags: ["commentaries"],
  },
  {
    publisher: "The Seattle Times",
    topic: "Sports",
    slug: "seattletimes-sports",
    url: "https://www.seattletimes.com/sports/feed/",
    sectionHints: ["sport"],
    description: "Sports news from The Seattle Times.",
    region: "US",
    language: "en",
    tags: ["sports"],
  },
  {
    publisher: "Raw Story",
    topic: "World",
    slug: "rawstory-world",
    url: "https://www.rawstory.com/feeds/world.rss",
    sectionHints: ["international"],
    description: "World news from Raw Story.",
    region: "US",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "Global News",
    topic: "All",
    slug: "globalnews-all",
    url: "https://globalnews.ca/feed/",
    sectionHints: ["international"],
    description: "All news from Global News.",
    region: "CA",
    language: "en",
    tags: ["news"],
  },
  {
    publisher: "Global News",
    topic: "World",
    slug: "globalnews-world",
    url: "https://globalnews.ca/world/feed/",
    sectionHints: ["international"],
    description: "World news from Global News.",
    region: "CA",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "Global News",
    topic: "Politics",
    slug: "globalnews-politics",
    url: "https://globalnews.ca/politics/feed/",
    sectionHints: ["politics"],
    description: "Political news from Global News.",
    region: "CA",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "Global News",
    topic: "Entertainment",
    slug: "globalnews-entertainment",
    url: "https://globalnews.ca/entertainment/feed/",
    sectionHints: ["entertainment"],
    description: "Entertainment news from Global News.",
    region: "CA",
    language: "en",
    tags: ["entertainment"],
  },
  {
    publisher: "Global News",
    topic: "Sports",
    slug: "globalnews-sports",
    url: "https://globalnews.ca/sports/feed/",
    sectionHints: ["sport"],
    description: "Sports news from Global News.",
    region: "CA",
    language: "en",
    tags: ["sports"],
  },
  {
    publisher: "Global News",
    topic: "Commentary",
    slug: "globalnews-commentary",
    url: "https://globalnews.ca/commentary/feed/",
    sectionHints: ["commentaries"],
    description: "Commentary from Global News.",
    region: "CA",
    language: "en",
    tags: ["commentary"],
  },
  {
    publisher: "South China Morning Post",
    topic: "All Articles",
    slug: "scmp-all-articles",
    url: "https://www.scmp.com/rss/91/feed/",
    sectionHints: ["international"],
    description: "All articles from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["news"],
  },
  {
    publisher: "South China Morning Post",
    topic: "China",
    slug: "scmp-china",
    url: "https://www.scmp.com/rss/4/feed/",
    sectionHints: ["international"],
    description: "China news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["china", "international"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Asia",
    slug: "scmp-asia",
    url: "https://www.scmp.com/rss/3/feed/",
    sectionHints: ["international"],
    description: "Asia news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["asia", "international"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Geopolitics",
    slug: "scmp-geopolitics",
    url: "https://www.scmp.com/rss/323047/feed/",
    sectionHints: ["international", "politics"],
    description: "Geopolitics news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["geopolitics", "international", "politics"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Politics",
    slug: "scmp-politics",
    url: "https://www.scmp.com/rss/323046/feed/",
    sectionHints: ["politics"],
    description: "Political news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Sport",
    slug: "scmp-sport",
    url: "https://www.scmp.com/rss/95/feed/",
    sectionHints: ["sport"],
    description: "Sports news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["sport"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Culture",
    slug: "scmp-culture",
    url: "https://www.scmp.com/rss/322296/feed/",
    sectionHints: ["culture"],
    description: "Culture news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["culture"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Tech",
    slug: "scmp-tech",
    url: "https://www.scmp.com/rss/36/feed/",
    sectionHints: ["tech"],
    description: "Technology news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Commentary",
    slug: "scmp-commentary",
    url: "https://www.scmp.com/rss/17/feed/",
    sectionHints: ["commentaries"],
    description: "Commentary from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["commentary"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Business",
    slug: "scmp-business",
    url: "https://www.scmp.com/rss/92/feed/",
    sectionHints: ["business"],
    description: "Business news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Southeast Asia",
    slug: "scmp-southeast-asia",
    url: "https://www.scmp.com/rss/318215/feed/",
    sectionHints: ["international"],
    description: "Southeast Asia news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["southeast-asia", "international"],
  },
  {
    publisher: "South China Morning Post",
    topic: "Hong Kong",
    slug: "scmp-hong-kong",
    url: "https://www.scmp.com/rss/2/feed/",
    sectionHints: ["international"],
    description: "Hong Kong news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["hong-kong", "international"],
  },
  {
    publisher: "South China Morning Post",
    topic: "China Economy",
    slug: "scmp-china-economy",
    url: "https://www.scmp.com/rss/318421/feed/",
    sectionHints: ["business", "international"],
    description: "China economy news from South China Morning Post.",
    region: "ASIA",
    language: "en",
    tags: ["china", "economy", "business"],
  },
  {
    publisher: "NPR",
    topic: "All Articles",
    slug: "npr-all-articles",
    url: "https://feeds.npr.org/1004/rss.xml",
    sectionHints: ["international"],
    description: "All articles from NPR.",
    region: "US",
    language: "en",
    tags: ["news"],
  },
  {
    publisher: "Sky News",
    topic: "Strange",
    slug: "skynews-strange",
    url: "https://feeds.skynews.com/feeds/rss/strange.xml",
    sectionHints: ["wildcard"],
    description: "Strange news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["strange", "wildcard"],
  },
  {
    publisher: "The Anomalist",
    topic: "Anomalies & Strange News",
    slug: "theanomalist-strange-news",
    url: "https://fetchrss.com/feed/Y0mVJVgpbfDCY0mU6DYvdbxS.rss",
    sectionHints: ["wildcard"],
    description: "Strange and unusual news stories from various sources.",
    region: "INT",
    language: "en",
    tags: ["strange", "unusual", "wildcard"],
  },
  {
    publisher: "Sky News",
    topic: "Entertainment",
    slug: "skynews-entertainment",
    url: "https://feeds.skynews.com/feeds/rss/entertainment.xml",
    sectionHints: ["entertainment"],
    description: "Entertainment news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["entertainment"],
  },
  {
    publisher: "Sky News",
    topic: "Technology",
    slug: "skynews-technology",
    url: "https://feeds.skynews.com/feeds/rss/technology.xml",
    sectionHints: ["tech"],
    description: "Technology news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["tech", "technology"],
  },
  {
    publisher: "Sky News",
    topic: "Politics",
    slug: "skynews-politics",
    url: "https://feeds.skynews.com/feeds/rss/politics.xml",
    sectionHints: ["politics"],
    description: "Political news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["politics"],
  },
  {
    publisher: "Sky News",
    topic: "US",
    slug: "skynews-us",
    url: "https://feeds.skynews.com/feeds/rss/us.xml",
    sectionHints: ["international"],
    description: "US news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["us", "international"],
  },
  {
    publisher: "Sky News",
    topic: "Business",
    slug: "skynews-business",
    url: "https://feeds.skynews.com/feeds/rss/business.xml",
    sectionHints: ["business"],
    description: "Business news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["business"],
  },
  {
    publisher: "Sky News",
    topic: "World",
    slug: "skynews-world",
    url: "https://feeds.skynews.com/feeds/rss/world.xml",
    sectionHints: ["international"],
    description: "World news from Sky News.",
    region: "UK",
    language: "en",
    tags: ["world", "international"],
  },
  {
    publisher: "Sky News",
    topic: "All Articles",
    slug: "skynews-all-articles",
    url: "https://feeds.skynews.com/feeds/rss/home.xml",
    sectionHints: ["international"],
    description: "All articles from Sky News.",
    region: "UK",
    language: "en",
    tags: ["news"],
  },
  {
    publisher: "ProPublica",
    topic: "Investigations",
    slug: "propublica-investigations",
    url: "https://www.propublica.org/feeds/propublica/main",
    sectionHints: ["commentaries"],
    description:
      "Investigative journalism and accountability reporting from ProPublica.",
    region: "US",
    language: "en",
    tags: ["investigations", "accountability", "commentaries"],
  },
  {
    publisher: "The Intercept",
    topic: "All Stories",
    slug: "intercept-all-stories",
    url: "https://theintercept.com/feed/",
    sectionHints: ["commentaries"],
    description:
      "Reporting, analysis, and investigations across The Intercept.",
    region: "US",
    language: "en",
    tags: ["investigations", "commentaries"],
  },
  {
    publisher: "The Intercept",
    topic: "World",
    slug: "intercept-world",
    url: "https://theintercept.com/world/feed/",
    sectionHints: ["international"],
    description: "Global coverage and geopolitics from The Intercept.",
    region: "US",
    language: "en",
    tags: ["international", "geopolitics"],
  },
  {
    publisher: "The Intercept",
    topic: "Politics",
    slug: "intercept-politics",
    url: "https://theintercept.com/politics/feed/",
    sectionHints: ["politics"],
    description: "Politics, policy, and power reporting from The Intercept.",
    region: "US",
    language: "en",
    tags: ["politics", "policy"],
  },
  {
    publisher: "The Intercept",
    topic: "Technology",
    slug: "intercept-technology",
    url: "https://theintercept.com/technology/feed/",
    sectionHints: ["tech"],
    description:
      "Technology, privacy, and security stories from The Intercept.",
    region: "US",
    language: "en",
    tags: ["technology", "privacy", "security"],
  },
  {
    publisher: "The Intercept",
    topic: "Voices",
    slug: "intercept-voices",
    url: "https://theintercept.com/voices/feed/",
    sectionHints: ["commentaries"],
    description: "Opinion and commentary essays from The Intercept Voices.",
    region: "US",
    language: "en",
    tags: ["commentaries", "opinion"],
  },
  {
    publisher: "The Intercept",
    topic: "Environment",
    slug: "intercept-environment",
    url: "https://theintercept.com/environment/feed/",
    sectionHints: ["science"],
    description:
      "Climate and environmental justice reporting from The Intercept.",
    region: "US",
    language: "en",
    tags: ["environment", "climate", "justice"],
  },
  {
    publisher: "Reveal",
    topic: "All Stories",
    slug: "reveal-all-stories",
    url: "https://revealnews.org/feed/",
    sectionHints: ["commentaries"],
    description:
      "Investigative reporting on inequity and injustice from Reveal.",
    region: "US",
    language: "en",
    tags: ["investigations", "inequality", "commentaries"],
  },
  {
    publisher: "Inside Climate News",
    topic: "All Stories",
    slug: "insideclimate-news",
    url: "https://insideclimatenews.org/feed/",
    sectionHints: ["science"],
    description:
      "Climate science, policy, and environment reporting from Inside Climate News.",
    region: "US",
    language: "en",
    tags: ["environment", "climate", "energy"],
  },
  {
    publisher: "Carbon Brief",
    topic: "All Stories",
    slug: "carbonbrief-all-stories",
    url: "https://www.carbonbrief.org/feed/",
    sectionHints: ["science"],
    description:
      "Climate science and energy policy analysis from Carbon Brief.",
    region: "UK",
    language: "en",
    tags: ["climate", "energy", "policy"],
  },
  {
    publisher: "Nature",
    topic: "Journal",
    slug: "nature-journal",
    url: "https://www.nature.com/nature.rss",
    sectionHints: ["science"],
    description: "Flagship science research and news from Nature.",
    region: "UK",
    language: "en",
    tags: ["science", "research"],
  },
  {
    publisher: "Science",
    topic: "News",
    slug: "science-news",
    url: "https://www.science.org/rss/news_current.xml",
    sectionHints: ["science"],
    description: "Latest science discoveries and analysis from Science.",
    region: "US",
    language: "en",
    tags: ["science", "research"],
  },
  {
    publisher: "New Scientist",
    topic: "Latest",
    slug: "newscientist-latest",
    url: "https://www.newscientist.com/feed/home/",
    sectionHints: ["science"],
    description: "Latest science and innovation coverage from New Scientist.",
    region: "UK",
    language: "en",
    tags: ["science", "innovation"],
  },
  {
    publisher: "New Scientist",
    topic: "Technology",
    slug: "newscientist-technology",
    url: "https://www.newscientist.com/subject/technology/feed/",
    sectionHints: ["tech"],
    description: "Technology news and future trends from New Scientist.",
    region: "UK",
    language: "en",
    tags: ["technology", "innovation"],
  },
  {
    publisher: "Aeon",
    topic: "Ideas",
    slug: "aeon-ideas",
    url: "https://aeon.co/feed.rss",
    sectionHints: ["culture"],
    description: "Essays on philosophy, culture, and society from Aeon.",
    region: "INT",
    language: "en",
    tags: ["culture", "philosophy", "essays"],
  },
  {
    publisher: "The Atlantic",
    topic: "All Stories",
    slug: "atlantic-all-stories",
    url: "https://www.theatlantic.com/feed/all/",
    sectionHints: ["culture"],
    description: "Reporting and analysis across channels from The Atlantic.",
    region: "US",
    language: "en",
    tags: ["culture", "politics", "commentaries"],
  },
  {
    publisher: "The Atlantic",
    topic: "Politics",
    slug: "atlantic-politics",
    url: "https://www.theatlantic.com/feed/channel/politics/",
    sectionHints: ["politics"],
    description: "Politics, policy, and democracy coverage from The Atlantic.",
    region: "US",
    language: "en",
    tags: ["politics", "policy"],
  },
  {
    publisher: "Longreads",
    topic: "Featured",
    slug: "longreads-featured",
    url: "https://longreads.com/feed/",
    sectionHints: ["culture"],
    description: "Curated longform stories and essays from Longreads.",
    region: "US",
    language: "en",
    tags: ["longform", "culture", "essays"],
  },
  {
    publisher: "TechCrunch",
    topic: "All Stories",
    slug: "techcrunch-all-stories",
    url: "https://techcrunch.com/feed/",
    sectionHints: ["tech"],
    description: "Startup and technology news from TechCrunch.",
    region: "US",
    language: "en",
    tags: ["startups", "technology", "venture"],
  },
  {
    publisher: "The Information",
    topic: "Technology",
    slug: "theinformation-technology",
    url: "https://www.theinformation.com/feed/",
    sectionHints: ["tech"],
    description:
      "In-depth reporting on technology and business from The Information.",
    region: "US",
    language: "en",
    tags: ["technology", "business", "analysis"],
  },
  {
    publisher: "Crunchbase News",
    topic: "Startups",
    slug: "crunchbase-startups",
    url: "https://news.crunchbase.com/feed/",
    sectionHints: ["business"],
    description:
      "Startup funding and venture capital updates from Crunchbase News.",
    region: "US",
    language: "en",
    tags: ["startups", "venture", "technology"],
  },
  {
    publisher: "The Japan Times",
    topic: "All Stories",
    slug: "japantimes-all-stories",
    url: "https://www.japantimes.co.jp/feed/",
    sectionHints: ["international"],
    description: "Japan and Asia-Pacific news from The Japan Times.",
    region: "ASIA",
    language: "en",
    tags: ["japan", "international"],
  },
  {
    publisher: "The Korea Herald",
    topic: "Life & Culture",
    slug: "koreaherald-life-culture",
    url: "https://www.koreaherald.com/rss/kh_LifenCulture",
    sectionHints: ["culture"],
    description: "Lifestyle and culture stories from The Korea Herald.",
    region: "ASIA",
    language: "en",
    tags: ["culture", "korea"],
  },
  {
    publisher: "The Korea Herald",
    topic: "Sports",
    slug: "koreaherald-sports",
    url: "https://www.koreaherald.com/rss/kh_Sports",
    sectionHints: ["sport"],
    description: "Sports news and updates from The Korea Herald.",
    region: "ASIA",
    language: "en",
    tags: ["sports", "korea"],
  },
  {
    publisher: "The Korea Herald",
    topic: "Opinion",
    slug: "koreaherald-opinion",
    url: "https://www.koreaherald.com/rss/kh_Opinion",
    sectionHints: ["commentaries"],
    description: "Opinion columns and editorials from The Korea Herald.",
    region: "ASIA",
    language: "en",
    tags: ["opinion", "commentaries", "korea"],
  },
  {
    publisher: "The Korea Herald",
    topic: "World",
    slug: "koreaherald-world",
    url: "https://www.koreaherald.com/rss/kh_World",
    sectionHints: ["international"],
    description: "Global headlines from The Korea Herald.",
    region: "ASIA",
    language: "en",
    tags: ["international", "korea"],
  },
  {
    publisher: "The Korea Herald",
    topic: "Business",
    slug: "koreaherald-business",
    url: "https://www.koreaherald.com/rss/kh_Business",
    sectionHints: ["business"],
    description: "Business and market coverage from The Korea Herald.",
    region: "ASIA",
    language: "en",
    tags: ["business", "markets", "korea"],
  },
  {
    publisher: "Taipei Times",
    topic: "All Stories",
    slug: "taipeitimes-all-stories",
    url: "https://www.taipeitimes.com/xml/index.rss",
    sectionHints: ["international"],
    description: "Taiwan and regional news from the Taipei Times.",
    region: "ASIA",
    language: "en",
    tags: ["taiwan", "international"],
  },
  {
    publisher: "The Conversation",
    topic: "Global",
    slug: "theconversation-global",
    url: "https://theconversation.com/global/home-page.atom",
    sectionHints: ["commentaries"],
    description:
      "Academic analysis and explanatory journalism from The Conversation.",
    region: "INT",
    language: "en",
    tags: ["analysis", "commentaries", "academia"],
  },
  {
    publisher: "Truthout",
    topic: "All Stories",
    slug: "truthout-all-stories",
    url: "https://truthout.org/feed/",
    sectionHints: ["commentaries"],
    description: "Independent reporting and commentary from Truthout.",
    region: "US",
    language: "en",
    tags: ["commentaries", "justice"],
  },
  {
    publisher: "Common Dreams",
    topic: "All Stories",
    slug: "commondreams-all-stories",
    url: "https://www.commondreams.org/feeds/feed.rss",
    sectionHints: ["commentaries"],
    description: "Progressive news and commentaries from Common Dreams.",
    region: "US",
    language: "en",
    tags: ["commentaries", "progressive"],
  },
  {
    publisher: "CounterPunch",
    topic: "All Stories",
    slug: "counterpunch-all-stories",
    url: "https://www.counterpunch.org/feed/",
    sectionHints: ["commentaries"],
    description: "Political analysis and essays from CounterPunch.",
    region: "US",
    language: "en",
    tags: ["commentaries", "analysis"],
  },
  {
    publisher: "Jacobin",
    topic: "All Stories",
    slug: "jacobin-all-stories",
    url: "https://www.jacobinmag.com/feed",
    sectionHints: ["commentaries"],
    description: "Socialist perspectives and analysis from Jacobin.",
    region: "US",
    language: "en",
    tags: ["commentaries", "politics"],
  },
  {
    publisher: "Salon",
    topic: "All Stories",
    slug: "salon-all-stories",
    url: "https://www.salon.com/feed/",
    sectionHints: ["commentaries"],
    description: "News, politics, and culture commentary from Salon.",
    region: "US",
    language: "en",
    tags: ["commentaries", "culture"],
  },
  {
    publisher: "VICE",
    topic: "All Stories",
    slug: "vice-all-stories",
    url: "https://www.vice.com/en/rss",
    sectionHints: ["culture"],
    description: "Global culture, politics, and tech stories from VICE.",
    region: "INT",
    language: "en",
    tags: ["culture", "youth", "international"],
  },
  {
    publisher: "Rolling Stone",
    topic: "All Stories",
    slug: "rollingstone-all-stories",
    url: "https://www.rollingstone.com/feed/",
    sectionHints: ["entertainment"],
    description: "Music, culture, and entertainment news from Rolling Stone.",
    region: "US",
    language: "en",
    tags: ["music", "culture", "entertainment"],
  },
];
