export const links: TopicLink[] = [
  {
    publisher: "ChannelNewsAsia",
    topic: "Asia",
    slug: "cna-asia",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6511",
    commentaryPrefix: "Commentary:",
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Business",
    slug: "cna-business",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6936",
    commentaryPrefix: "Commentary:",
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Latest",
    slug: "cna-latest",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml",
    commentaryPrefix: "Commentary:",
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Singapore",
    slug: "cna-singapore",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10416",
    commentaryPrefix: "Commentary:",
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "Sport",
    slug: "cna-sport",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=10296",
    commentaryPrefix: "Commentary:",
  },
  {
    publisher: "ChannelNewsAsia",
    topic: "World",
    slug: "cna-world",
    url: "https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml&category=6311",
    commentaryPrefix: "Commentary:",
  },
  {
    publisher: "The New York Times",
    topic: "Bret Stephens",
    slug: "nyt-bret-stephens",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/bret-stephens/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Charles M. Blow",
    slug: "nyt-charles-blow",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/charles-m-blow/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "David Brooks",
    slug: "nyt-david-brooks",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/david-brooks/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Ezra Klein",
    slug: "nyt-ezra-klein",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ezra-klein/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Farhad Manjoo",
    slug: "nyt-farhad-manjoo",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/farhad-manjoo/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Frank Bruni",
    slug: "nyt-frank-bruni",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/frank-bruni/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Gail Collins",
    slug: "nyt-gail-collins",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/gail-collins/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Jamelle Bouie",
    slug: "nyt-jamelle-bouie",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/jamelle-bouie/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Maureen Dowd",
    slug: "nyt-maureen-dowd",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/maureen-dowd/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Michelle Goldberg",
    slug: "nyt-michelle-goldberg",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/michelle-goldberg/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Nicholas Kristof",
    slug: "nyt-nicholas-kristof",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/nicholas-kristof/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Paul Krugman",
    slug: "nyt-paul-krugman",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/paul-krugman/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Ross Douthat",
    slug: "nyt-ross-douthat",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/ross-douthat/rss.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Sunday Review",
    slug: "nyt-sunday-review",
    url: "https://rss.nytimes.com/services/xml/rss/nyt/sunday-review.xml",
  },
  {
    publisher: "The New York Times",
    topic: "Thomas L. Friedman",
    slug: "nyt-thomas-friedman",
    url: "https://www.nytimes.com/svc/collections/v1/publish/www.nytimes.com/column/thomas-l-friedman/rss.xml",
  },
  {
    publisher: "The Wall Street Journal",
    topic: "Opinion",
    slug: "wsj-opinion",
    url: "https://feeds.content.dowjones.io/public/rss/RSSOpinion",
  },
  {
    publisher: "The Washington Post",
    topic: "George F. Will",
    slug: "wapo-george-will",
    url: "https://www.washingtonpost.com/arcio/rss/author/George%20F%20-Will/",
  },
  {
    publisher: "The Washington Post",
    topic: "Opinions",
    slug: "wapo-opinions",
    url: "https://www.washingtonpost.com/arcio/rss/category/opinions/?itid=lk_inline_manual_5",
  },
];
